name: Update Empty JSON-LD URLs v2.3
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-jsonld-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Find and update empty URLs in JSON-LD schema
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        echo "Repository name: $REPO_NAME"
        
        find . -type f -name "*.html" | while read -r htmlFile; do
          echo "Processing file: $htmlFile"
          
          # Get the relative path from the root of the repository
          relativePath="${htmlFile#./}"
          dirPath=$(dirname "$relativePath")
          fileName=$(basename "$htmlFile" .html)
          
          # Special handling for index.html files
          if [ "$fileName" = "index" ]; then
            if [ "$dirPath" = "." ]; then
              urlPath=""  # Homepage
            else
              urlPath="/$dirPath"  # Index in subfolder
            fi
          else
            # Regular files
            if [ "$dirPath" = "." ]; then
              urlPath="/$fileName"
            else
              urlPath="/$dirPath/$fileName"
            fi
          fi
          
          # Remove any double slashes that might occur and encode spaces
          urlPath=$(echo "$urlPath" | sed 's#//#/#g' | sed 's/ /%20/g')
          
          # Construct the full URL
          fullURL="https://$REPO_NAME$urlPath"
          baseURL="https://$REPO_NAME"
          echo "Generated URL for $htmlFile: $fullURL"
          
          # Escape special characters for perl
          escapedURL=$(printf '%s\n' "$fullURL" | sed 's:[][\/.^$*]:\\&:g')
          escapedBaseURL=$(printf '%s\n' "$baseURL" | sed 's:[][\/.^$*]:\\&:g')
          
          perl -i -0777 -e 'while (<>) {
              s/(<script type="application\/ld\+json" class="rank-math-schema">)(.*?)(<\/script>)/
                my $start = $1;
                my $json = $2;
                my $end = $3;
                
                $json =~ s/"@id":\s*"((?!https:\/\/secure\.gravatar\.com\/)(?!'"$escapedBaseURL"')[^"]+|)"/"@id":"'"$escapedURL"'"/g;
                $json =~ s/"url":\s*"((?!https:\/\/secure\.gravatar\.com\/)(?!'"$escapedBaseURL"')[^"]+|)"/"url":"'"$escapedURL"'"/g;
                $json =~ s/"item":\s*\{"@id":\s*"((?!https:\/\/secure\.gravatar\.com\/)(?!'"$escapedBaseURL"')[^"]+|)"/"item":{"@id":"'"$escapedURL"'"/g;
                
                $start . $json . $end
              /ge;
              print;
            }' "$htmlFile"
          
          if [ -s "$htmlFile" ]; then
            echo "Successfully processed $htmlFile"
          else
            echo "Warning: Empty output file generated for $htmlFile"
          fi
        done
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update all incorrect URLs in JSON-LD schema" || echo "No changes to commit"
        git push origin HEAD:main || echo "No changes to push"
