name: Update Schema JSON-LD URLs v3.0 perl
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-jsonld-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Perl Script for Updating JSON-LD URLs
      run: |
        cat <<'EOF' > update_jsonld.pl
        #!/usr/bin/perl

        use strict;
        use warnings;

        # Get arguments passed to the script
        my ($htmlFile, $escapedURL, $escapedBaseURL) = @ARGV;

        # Open the file for reading
        open my $fh, '<', $htmlFile or die "Could not open '$htmlFile' for reading: $!";
        local $/; # Enable slurp mode
        my $content = <$fh>;
        close $fh;

        # Perform the substitutions
        $content =~ s{(<script type="application/ld\+json" class="rank-math-schema">)(.*?)(</script>)}{
            my $start = $1;
            my $json = $2;
            my $end = $3;

            $json =~ s{"@id":\s*"(?!https://secure\.gravatar\.com/)(?!\Q$escapedBaseURL\E)[^"]*"}{"@id":"$escapedURL"}g;
            $json =~ s{"url":\s*"(?!https://secure\.gravatar\.com/)(?!\Q$escapedBaseURL\E)[^"]*"}{"url":"$escapedURL"}g;
            $json =~ s{"item":\s*\{"@id":\s*"(?!https://secure\.gravatar\.com/)(?!\Q$escapedBaseURL\E)[^"]*"}{"item":{"@id":"$escapedURL"}g;

            $start . $json . $end;
        }ge;

        # Write the updated content back to the file
        open my $out, '>', $htmlFile or die "Could not open '$htmlFile' for writing: $!";
        print $out $content;
        close $out;
        EOF

        chmod +x update_jsonld.pl

    - name: Update Empty URLs in JSON-LD Schema
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        echo "Repository name: $REPO_NAME"

        find . -type f -name "*.html" | while read -r htmlFile; do
          echo "Processing file: $htmlFile"

          # Construct URLs
          relativePath="${htmlFile#./}"
          dirPath=$(dirname "$relativePath")
          fileName=$(basename "$htmlFile" .html)

          if [ "$fileName" = "index" ]; then
            if [ "$dirPath" = "." ]; then
              urlPath=""  # Homepage
            else
              urlPath="/$dirPath"  # Index in subfolder
            fi
          else
            if [ "$dirPath" = "." ]; then
              urlPath="/$fileName"
            else
              urlPath="/$dirPath/$fileName"
            fi
          fi

          # Remove double slashes and encode spaces
          urlPath=$(echo "$urlPath" | sed 's#//#/#g' | sed 's/ /%20/g')

          # Construct full and base URLs
          fullURL="https://$REPO_NAME$urlPath"
          baseURL="https://$REPO_NAME"

          # Debugging outputs
          echo "Generated URL: $fullURL"
          echo "Base URL: $baseURL"

          # Call the external Perl script
          ./update_jsonld.pl "$htmlFile" "$fullURL" "$baseURL"
        done

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update all incorrect URLs in JSON-LD schema" || echo "No changes to commit"
        git push origin HEAD:main || echo "No changes to push"
